# Generated by Django 2.0.5 on 2018-07-25 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyParameterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_data', models.FloatField()),
                ('body_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='bodyparameter',
            name='body_data',
        ),
        migrations.RemoveField(
            model_name='bodyparameter',
            name='body_datetime',
        ),
        migrations.RemoveField(
            model_name='targetbodyparameter',
            name='target_body_title',
        ),
        migrations.RemoveField(
            model_name='targetbodyparameter',
            name='user',
        ),
        migrations.AddField(
            model_name='targetbodyparameter',
            name='target_parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.BodyParameter'),
        ),
        migrations.AddField(
            model_name='bodyparameterdata',
            name='user_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.BodyParameter'),
        ),
    ]
