# Generated by Django 2.0.5 on 2018-07-25 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0002_auto_20180725_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbodyparameter',
            name='target_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.BodyParameter'),
        ),
    ]
