# Generated by Django 2.0.5 on 2018-10-01 13:28

import FitnessPersonalArea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0005_projectionphoto_projection_view_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionphoto',
            name='projection_view_photo',
            field=models.ImageField(default=None, height_field='image_height', max_length=200, upload_to=FitnessPersonalArea.models.projection_photo_path, verbose_name='account photo', width_field='image_width'),
        ),
    ]
