# Generated by Django 2.0.5 on 2018-06-16 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_user_type', models.CharField(choices=[('TRN', 'Trainer'), ('USL', 'Usual')], default='USL', max_length=3)),
                ('fitness_user_photo', models.ImageField(height_field='image_height', null=True, upload_to='profiles_photo/%Y/%m/%d/', width_field='image_width')),
                ('fitness_user_gender', models.CharField(choices=[('MAL', 'Male'), ('FEM', 'Female'), ('OTH', 'Other')], default='MAL', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
