# Generated by Django 2.0.5 on 2018-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetbodyparameter',
            name='target_body_title',
            field=models.CharField(max_length=100),
        ),
    ]
