# Generated by Django 2.0.5 on 2018-06-16 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_employment_status', models.BooleanField(default=False)),
                ('trainer_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=1000)),
                ('doc_file', models.FileField(upload_to='trainer_docs/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessTrainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=100)),
                ('gym_description', models.CharField(max_length=1000)),
                ('gym_destination', models.CharField(max_length=100)),
                ('gym_geolocation', django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default={'latitude': 0.0, 'longitude': 0.0})),
                ('gym_open_for_trainings', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessTrainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_price_hour', models.FloatField()),
                ('trainer_price_currency', models.CharField(max_length=20)),
                ('trainer_price_creating_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('trainer_price_bargaining', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessTrainer')),
            ],
        ),
        migrations.AddField(
            model_name='fitnessuser',
            name='fitness_user_destination_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_photo',
            field=models.ImageField(default=None, height_field='image_height', upload_to='profiles_photo/%Y/%m/%d/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='fitnesstrainer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser'),
        ),
    ]
