# Generated by Django 2.0.5 on 2018-07-15 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0002_auto_20180715_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traingym',
            name='gym_geo',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
