# Generated by Django 2.0.5 on 2018-06-18 00:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0002_auto_20180616_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(default=django.utils.timezone.now)),
                ('schedule_train_end', models.TimeField(default=django.utils.timezone.now)),
                ('schedule_train_start', models.TimeField(default=django.utils.timezone.now)),
                ('schedule_train_type', models.CharField(max_length=100)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_schedule_user', to='FitnessPersonalArea.FitnessUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainergym',
            name='gym_open_for_trainings',
        ),
        migrations.AlterField(
            model_name='trainergym',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser'),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='schedule_gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_gym', to='FitnessPersonalArea.TrainerGym'),
        ),
        migrations.AddField(
            model_name='trainschedule',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_schedule_user', to='FitnessPersonalArea.FitnessUser'),
        ),
    ]
