# Generated by Django 2.0.5 on 2018-06-18 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0003_auto_20180618_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstrainer',
            name='trainer_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_destination_city',
            field=models.CharField(default='', max_length=50, verbose_name='destination city'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_gender',
            field=models.CharField(choices=[('MAL', 'Male'), ('FEM', 'Female'), ('OTH', 'Other')], default='MAL', max_length=3, verbose_name='user gender'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_photo',
            field=models.ImageField(default=None, height_field='image_height', upload_to='profiles_photo/%Y/%m/%d/', verbose_name='account photo', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_type',
            field=models.CharField(choices=[('TRN', 'Trainer'), ('USL', 'Usual')], default='USL', max_length=3, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
