# Generated by Django 2.0.5 on 2018-06-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0003_auto_20180618_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcontract',
            name='contract_end_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainingpayment',
            name='payment_training_schedule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.TrainingSchedule'),
        ),
    ]
