# Generated by Django 2.0.5 on 2018-07-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0003_auto_20180725_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyparameter',
            name='body_show',
            field=models.BooleanField(default=True),
        ),
    ]
