# Generated by Django 2.0.5 on 2018-06-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0004_auto_20180618_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerDocs',
            new_name='TrainerDoc',
        ),
    ]
