# Generated by Django 2.0.5 on 2018-06-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0004_auto_20180618_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcontract',
            name='contract_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
