# Generated by Django 2.0.5 on 2018-06-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0006_auto_20180618_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingpayment',
            name='payment_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
