# Generated by Django 2.0.5 on 2018-06-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0007_auto_20180618_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingpayment',
            old_name='payment_user_target',
            new_name='payment_user_ward',
        ),
        migrations.RenameField(
            model_name='trainingpayment',
            old_name='payment_target_success',
            new_name='payment_ward_success',
        ),
    ]
