# Generated by Django 2.0.5 on 2018-06-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0008_auto_20180618_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traingym',
            name='gym_description',
            field=models.TextField(max_length=1000),
        ),
    ]
