# Generated by Django 2.0.5 on 2018-06-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0009_auto_20180619_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_alive', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(to='FitnessPersonalArea.FitnessUser')),
            ],
        ),
    ]
