# Generated by Django 2.0.5 on 2018-06-19 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0010_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=1000)),
                ('message_file', models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/')),
                ('message_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser')),
            ],
        ),
    ]
