# Generated by Django 2.0.5 on 2018-06-19 23:26

import FitnessPersonalArea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0011_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to=FitnessPersonalArea.models.chat_directory_path),
        ),
    ]
