# Generated by Django 2.0.5 on 2018-06-19 23:40

import FitnessPersonalArea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0012_auto_20180619_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_photo',
            field=models.ImageField(default=None, height_field='image_height', upload_to=FitnessPersonalArea.models.profile_photo_path, verbose_name='account photo', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='projectionphoto',
            name='projection_view_photo',
            field=models.ImageField(default=None, height_field='image_height', upload_to=FitnessPersonalArea.models.projection_photo_path, verbose_name='account photo', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='trainerdoc',
            name='doc_file',
            field=models.FileField(upload_to=FitnessPersonalArea.models.trainer_docs_path),
        ),
    ]
