# Generated by Django 2.0.5 on 2018-06-21 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0013_auto_20180619_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=100)),
                ('feedback_text', models.TextField(max_length=4000)),
                ('feedback_rate', models.PositiveSmallIntegerField(default=0)),
                ('feedback_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_gender',
            field=models.CharField(choices=[('MAL', 'Мужчина'), ('FEM', 'Женщина'), ('OTH', 'Другой')], default='MAL', max_length=3, verbose_name='user gender'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_type',
            field=models.CharField(choices=[('TRN', 'Тренер'), ('USL', 'Подопечный')], default='USL', max_length=3, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='projectionphoto',
            name='projection_view_type',
            field=models.CharField(choices=[('FRT', 'Передний вид'), ('SD1', 'Боковой вид №1'), ('SD2', 'Боковой вид №2'), ('BCK', 'Задний вид')], default='FRT', max_length=3, verbose_name='projection type'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_feedback_user', to='FitnessPersonalArea.FitnessUser'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_feedback_user', to='FitnessPersonalArea.FitnessUser'),
        ),
    ]
