# Generated by Django 2.0.5 on 2018-06-30 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0014_auto_20180621_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_readed',
            field=models.BooleanField(default=False),
        ),
    ]
