# Generated by Django 2.0.5 on 2018-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0016_auto_20180701_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defexercise',
            name='exercise_type',
            field=models.ManyToManyField(blank=True, to='FitnessPersonalArea.DefExerciseType'),
        ),
        migrations.AlterField(
            model_name='deftypesbundle',
            name='bundle_subtypes',
            field=models.ManyToManyField(blank=True, related_name='bundled_subtypes', to='FitnessPersonalArea.DefExerciseType'),
        ),
    ]
