# Generated by Django 2.0.5 on 2018-07-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0017_auto_20180701_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defexercise',
            name='exercise_approaches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='defexercise',
            name='exercise_type',
        ),
        migrations.AddField(
            model_name='defexercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitnessPersonalArea.DefExerciseType'),
        ),
    ]
