# Generated by Django 2.0.5 on 2018-07-02 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0018_auto_20180701_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_title', models.CharField(max_length=100)),
                ('exercise_description', models.TextField(max_length=5000)),
                ('exercise_approaches', models.IntegerField(blank=True, default=0, null=True)),
                ('exercise_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_title', models.CharField(max_length=100)),
                ('set_description', models.TextField(max_length=5000)),
                ('set_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('set_def_exercises', models.ManyToManyField(blank=True, to='FitnessPersonalArea.DefExercise')),
                ('set_exercises', models.ManyToManyField(blank=True, to='FitnessPersonalArea.Exercise')),
                ('set_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=100)),
                ('type_description', models.TextField(max_length=5000)),
                ('type_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SharedExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_rate', models.FloatField(default=0)),
                ('shared_copies', models.IntegerField(default=0)),
                ('shared_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_exercises', models.ManyToManyField(to='FitnessPersonalArea.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='SharedSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_rate', models.FloatField(default=0)),
                ('shared_copies', models.IntegerField(default=0)),
                ('shared_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('shared_set', models.ManyToManyField(to='FitnessPersonalArea.ExerciseSet')),
            ],
        ),
        migrations.CreateModel(
            name='TypesBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bundle_subtypes', models.ManyToManyField(blank=True, related_name='bundled_subtypes', to='FitnessPersonalArea.ExerciseType')),
                ('bundle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundled_type', to='FitnessPersonalArea.ExerciseType')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitnessPersonalArea.ExerciseType'),
        ),
    ]
