# Generated by Django 2.0.5 on 2018-07-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0019_auto_20180702_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='type_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser'),
        ),
    ]
