# Generated by Django 2.0.5 on 2018-07-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0020_exercisetype_type_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetype',
            name='type_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessUser'),
        ),
    ]
