# Generated by Django 2.0.5 on 2018-07-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0021_auto_20180702_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedexercise',
            name='shared_exercises',
        ),
        migrations.AddField(
            model_name='sharedexercise',
            name='shared_exercise',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.Exercise'),
        ),
    ]
