# Generated by Django 2.0.5 on 2018-07-02 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0022_auto_20180702_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedexercise',
            name='shared_exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.Exercise'),
        ),
    ]
