# Generated by Django 2.0.5 on 2018-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0023_auto_20180702_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_rate',
            field=models.FloatField(default=0),
        ),
    ]
