# Generated by Django 2.0.5 on 2018-07-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0025_auto_20180702_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedset',
            name='shared_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.ExerciseSet'),
        ),
    ]
