# Generated by Django 2.0.5 on 2018-07-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0026_auto_20180702_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_gender',
            field=models.CharField(choices=[('MAL', 'Мужчина'), ('FEM', 'Женщина'), ('SEC', 'Секрет')], default='MAL', max_length=3, verbose_name='user gender'),
        ),
    ]
