# Generated by Django 2.0.5 on 2018-07-05 15:13

import FitnessPersonalArea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0027_auto_20180705_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_photo',
            field=models.ImageField(blank=True, default=None, height_field='image_height', null=True, upload_to=FitnessPersonalArea.models.profile_photo_path, verbose_name='account photo', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_type',
            field=models.CharField(choices=[('TRN', 'Тренер'), ('WRD', 'Подопечный')], default='WRD', max_length=3, verbose_name='user type'),
        ),
    ]
