# Generated by Django 2.0.5 on 2018-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0028_auto_20180705_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessuser',
            name='fitness_user_destination_city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='destination city'),
        ),
    ]
