# Generated by Django 2.0.5 on 2018-07-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0029_auto_20180705_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerdoc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitnessPersonalArea.FitnessTrainer'),
        ),
    ]
