# Generated by Django 2.0.5 on 2018-07-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0030_auto_20180707_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprice',
            name='trainer_price_actuality',
            field=models.BooleanField(default=True),
        ),
    ]
