# Generated by Django 2.0.5 on 2018-07-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0031_trainerprice_trainer_price_actuality'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprice',
            name='trainer_price_comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
