# Generated by Django 2.0.5 on 2018-07-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0032_trainerprice_trainer_price_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprice',
            name='trainer_price_show',
            field=models.BooleanField(default=True),
        ),
    ]
