# Generated by Django 2.0.5 on 2018-07-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0033_trainerprice_trainer_price_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessuser',
            name='fitness_user_bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
