# Generated by Django 2.0.5 on 2018-07-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0034_fitnessuser_fitness_user_bdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='schedule_exercise_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FitnessPersonalArea.ExerciseSet'),
        ),
    ]
