# Generated by Django 2.0.5 on 2018-07-08 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0035_trainingschedule_schedule_exercise_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcontract',
            name='contract_create_datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trainingcontract',
            name='contract_expire_datetime',
            field=models.DateField(),
        ),
    ]
