# Generated by Django 2.0.5 on 2018-07-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0036_auto_20180708_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnesstrainer',
            name='trainer_description',
            field=models.TextField(default='Description', max_length=5000),
        ),
    ]
