# Generated by Django 2.0.5 on 2018-07-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0037_auto_20180711_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiary',
            name='diary_note_show',
            field=models.BooleanField(default=True),
        ),
    ]
