# Generated by Django 2.0.5 on 2018-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPersonalArea', '0038_userdiary_diary_note_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalnote',
            name='medical_note_show',
            field=models.BooleanField(default=True),
        ),
    ]
